[package]
name = "date_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
date_utils = { git = "https://github.com/alexnodus/date_utils.git" }
